"""Independent Mirai Project Capsule validation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator

from .canonical import digest_value

FORBIDDEN = {"approval", "approvals", "approval_receipt", "capability", "capabilities", "capability_grant", "capability_grants", "canonical_write_allowed"}


def _load_yaml(filename: Path) -> dict[str, Any]:
    class UniqueLoader(yaml.SafeLoader):
        pass

    def construct_mapping(loader: UniqueLoader, node: yaml.Node, deep: bool = False) -> dict[str, Any]:
        mapping: dict[str, Any] = {}
        for key_node, value_node in node.value:
            key = loader.construct_object(key_node, deep=deep)
            if key in mapping:
                raise ValueError(f"duplicate_yaml_key:{key}")
            mapping[key] = loader.construct_object(value_node, deep=deep)
        return mapping

    UniqueLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, construct_mapping)
    value = yaml.load(filename.read_text(encoding="utf-8"), Loader=UniqueLoader)
    if not isinstance(value, dict):
        raise ValueError("yaml_root_must_be_object")
    return value


def _schema_errors(value: Any, schema: dict[str, Any], label: str) -> list[str]:
    return sorted(f"{label}:schema:{'/'.join(str(x) for x in error.absolute_path) or '/'}:{error.message}" for error in Draft202012Validator(schema).iter_errors(value))


def _authority_errors(value: Any, pointer: str = "manifest") -> list[str]:
    errors: list[str] = []
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN:
                errors.append(f"manifest:authority_minting:{pointer}.{key}")
            errors.extend(_authority_errors(child, f"{pointer}.{key}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            errors.extend(_authority_errors(child, f"{pointer}[{index}]"))
    return errors


def _file_digest(filename: Path) -> str:
    return f"sha256:{hashlib.sha256(filename.read_bytes()).hexdigest()}"


def _path_digest(root: Path, relative: str, sources: str) -> str:
    target = (root / relative).resolve()
    if root != target and root not in target.parents:
        raise ValueError(f"path_escape:{relative}")
    if not target.exists():
        return digest_value({"missing": relative})
    if target.is_symlink():
        raise ValueError(f"symlink_entrypoint_not_allowed:{relative}")
    if target.is_file():
        return digest_value(_load_yaml(target)) if relative == sources else _file_digest(target)
    entries: list[dict[str, str]] = []
    for item in sorted(target.rglob("*")):
        if item.is_symlink():
            raise ValueError(f"symlink_entrypoint_not_allowed:{item.relative_to(root).as_posix()}")
        if item.is_file():
            entries.append({"path": item.relative_to(root).as_posix(), "digest": _file_digest(item)})
    return digest_value(entries)


def _entrypoint_paths_ordered(manifest: dict[str, Any]) -> list[str]:
    entrypoints = manifest["entrypoints"]
    graph = entrypoints["graph"]
    paths = [graph["root"], *graph["objects"], *graph["relations"], entrypoints["sources"]]
    paths.extend(entrypoints[key] for key in ("programs", "components", "policies", "interfaces", "context") if entrypoints.get(key))
    return list(dict.fromkeys(paths))


def _entrypoint_paths(manifest: dict[str, Any]) -> list[str]:
    return sorted(_entrypoint_paths_ordered(manifest))


def _generate_start(lock: dict[str, Any], owner_notes: str) -> str:
    manifest = lock["manifest"]
    project = manifest["project"]
    lines = [
        "<!-- GENERATED BY MIRAI. Edit mirai/owner-notes.md, then run `mirai project compile`. -->",
        f"# {project['title']}", "", f"- Project: `{project['id']}`", f"- Kind: `{project['kind']}`",
        f"- Mirai: `{manifest['requires']['mirai']}`", f"- Project manifest contract: `{manifest['contract_version']}`",
        f"- Lock digest: `{lock['digest']}`", f"- Profiles: {', '.join(f'`{item}`' for item in manifest['profiles'])}", "",
        "## Boundaries", "", "Mirai uses Hybrid SOT. Generated context and evidence do not authorize canonical updates. Canonical writes require owner approval. Runtime must use the verified lock, not mutable YAML.", "",
        "## Entry Points", "", *[f"- `{item}`" for item in _entrypoint_paths_ordered(manifest)]
    ]
    note = owner_notes.strip()
    if note:
        lines.extend(["", "## Owner Notes", "", note])
    lines.append("")
    return "\n".join(lines)


def check_project(root: str | Path, schemas: str | Path, agent_brief: str | Path | None = None) -> dict[str, Any]:
    project_root = Path(root).resolve()
    schema_root = Path(schemas).resolve()
    errors: list[str] = []
    project_lock_digest: str | None = None
    agent_brief_digest: str | None = None
    try:
        manifest = _load_yaml(project_root / "mirai/manifest.yaml")
        lock = json.loads((project_root / "mirai/manifest.lock.json").read_text(encoding="utf-8"))
        project_lock_digest = lock.get("digest")
        manifest_schema = json.loads((schema_root / "mirai-project-manifest.schema.json").read_text(encoding="utf-8"))
        lock_schema = json.loads((schema_root / "mirai-project-lock.schema.json").read_text(encoding="utf-8"))
        errors.extend(_schema_errors(manifest, manifest_schema, "manifest"))
        errors.extend(_schema_errors(lock, lock_schema, "lock"))
        errors.extend(_authority_errors(manifest))
        if manifest != lock.get("manifest"):
            errors.append("lock:manifest_mismatch")
        body = {key: value for key, value in lock.items() if key != "digest"}
        if digest_value(body) != lock.get("digest"):
            errors.append("lock:digest_mismatch")
        sources = manifest["entrypoints"]["sources"]
        computed = {relative: _path_digest(project_root, relative, sources) for relative in _entrypoint_paths(manifest)}
        if computed != lock.get("entrypoint_digests"):
            errors.append("lock:entrypoint_digest_mismatch")
        if computed.get(sources) != lock.get("source_reference_digest"):
            errors.append("lock:source_reference_digest_mismatch")
        start = (project_root / manifest["documentation"]["start"]).read_text(encoding="utf-8")
        notes_file = project_root / manifest["documentation"]["owner_notes"]
        expected_start = _generate_start(lock, notes_file.read_text(encoding="utf-8") if notes_file.exists() else "")
        if start != expected_start:
            errors.append("start:generated_content_mismatch")
        facade = json.loads((project_root / "graph.json").read_text(encoding="utf-8"))
        if facade.get("id") != manifest["project"]["id"] or facade.get("graph", {}).get("root") != manifest["entrypoints"]["graph"]["root"]:
            errors.append("facade:identity_or_root_mismatch")
        if (project_root / "graph").exists():
            errors.append("facade:duplicate_graph_root")
        if agent_brief:
            brief = json.loads(Path(agent_brief).read_text(encoding="utf-8"))
            agent_brief_digest = brief.get("digest")
            brief_schema = json.loads((schema_root / "mirai-agent-brief.schema.json").read_text(encoding="utf-8"))
            errors.extend(_schema_errors(brief, brief_schema, "brief"))
            brief_body = {key: value for key, value in brief.items() if key != "digest"}
            if digest_value(brief_body) != brief.get("digest"):
                errors.append("brief:digest_mismatch")
            if brief.get("canonical_write_allowed") is not False or brief.get("lock", {}).get("digest") != lock.get("digest"):
                errors.append("brief:authority_or_lock_mismatch")
    except Exception as error:  # fail closed at the independent boundary
        errors.append(f"project:{type(error).__name__}:{error}")
    return {"contract_version": "1.0.0", "implementation": "python_independent", "kind": "mirai_project_capsule", "status": "passed" if not errors else "failed", "errors": sorted(set(errors)), "project_lock_digest": project_lock_digest, "agent_brief_digest": agent_brief_digest, "canonical_write_performed": False, "effects_executed": False}
